### ISSUE TITLE
[Question] Reworking the Trait

### ISSUE THREAD

**Issue by mcordingley** [paragonie/eloquent-ciphersweet#6]
I'm getting to the point with my alterations that I'm bumping up against the Model trait and would really like parts of it to be different. I know that you said this is currently an "experimental" "toy" implementation. How attached are you to the current implementation and how much change would you be tolerant of in the next few PRs from me? I've tried to keep PRs additive thus far, but have reached the point where the commits need to start changing things that already exist.

**Comment by mcordingley** [comment]
I think I'm going to go with simply making the changes and then seeing if you like the PR.

**Comment by paragonie-scott** [comment]
Hey Michael,

Sorry for not responding sooner. Yesterday was crazy.

> How attached are you to the current implementation and how much change would you be tolerant of in the next few PRs from me? 

I'm not attached at all. I'm actually still noodling over the most effective way to make the blind indexes user-friendly for search operations. That probably requires rewriting some parts of what I started with, depending on where it lands.

If you have any ideas, please feel free to implement them.

**Comment by mcordingley** [comment]
Awesome. I'll build it out as time permits between work and family. I think it highly probable that I'll come back with a wish-list of things, mostly ergonomic, from the base CipherSweet package. I'll be pushing changes to my branch on GitHub as I build it up, if you're curious to see the progress.

**Comment by paragonie-scott** [comment]
A wish list is very helpful. My hands-on experience with Laravel several versions out of date (4.1/4.2), so having some insight on what Laravel developers *want* is incredibly useful.

**Comment by mcordingley** [comment]
I'll start opening issues, then. :+1:

**Comment by mcordingley** [comment]
Actually, it's far more efficient for me to send you a series of PRs to the base CipherSweet package instead of opening issues with desires.

Some of them represent backwards compatibility breaks, which entails a new major release number per semver. I hope that you'll be OK with this, can release a 2.0 with the stream-lining, and go from there. I would recommend/ask you to make a side branch over there to aggregate my PRs and to represent the "next" major version, so as to not force a new major version immediately. This would also mean that I could break up my changes into smaller PRs for discussion and tweaking before ultimate inclusion.

I know you generally want to support some EOL versions of PHP because you target inclusion by major projects that have similarly wide PHP version support. A new major version number is a great time to bump minimum PHP requirements. If you're wanting to bump minimum PHP version with a major release, just let me know what the new minimum target is and I'll build with that in mind. Personal preference is for 7.2+, since 7.0 and older are EOL, 7.1 will be soon, and 7.2 has native sodium support, which can be a nice assumption to build against.

**Comment by paragonie-scott** [comment]
If we increase the minimum PHP version, it will be after the year is over, and probably towards PHP 7.2. Reasoning: If WordPress of all projects can drop PHP <7.2 by the end of the year, no other project has any excuse.

**Comment by mcordingley** [comment]
> If WordPress of all projects can drop PHP <7.2 by the end of the year, no other project has any excuse.

It's a minor miracle that this is even a possibility.

**Comment by paragonie-scott** [comment]
It is, and I had very little to do with that decision. I'm hoping they overall adopt better habits for security going forward.

**Comment by paragonie-scott** [comment]
> Some of them represent backwards compatibility breaks, which entails a new major release number per semver. 

Was this one of the possibly-breaking changes you had in mind? https://github.com/paragonie/ciphersweet/pull/40

**Comment by mcordingley** [comment]
Not really. I have [a branch](https://github.com/mcordingley/ciphersweet/tree/ignorance-is-bliss) right now with some of the breaking changes.

**Comment by mcordingley** [comment]
One thing that's killing me is that I need to be able to get a blind index `type` for a named blind index without having to supply a bunch of other information. That would enable some nice integration with the query builder by being able to add `whereBlind($indexName, $searchValue)`

**Comment by paragonie-scott** [comment]
Easily done. I'll add that in `v1.10.0`.

**Comment by mcordingley** [comment]
Awesome. Thanks!

**Comment by mcordingley** [comment]
Other thing is that it'd be nice to be able to calculate blind index values without having to pass a complete row representation to it. Just the values involved in the index. It's been a bit since I had the time to look at this, so my memory may be faulty.

**Comment by paragonie-scott** [comment]
I'm pretty sure that's already supported, but I'll write a unit test to make sure.

**Comment by paragonie-scott** [comment]
Unit test is alive here: https://github.com/paragonie/ciphersweet/pull/41/commits/9f6557671f65f55ad0d674805141f906502afafe
